# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - FloraFlow

on:
  push:
    branches:
      - fullproject-abel
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Set project path
        id: detect
        shell: pwsh
        run: |
          $projectPath = "$env:GITHUB_WORKSPACE/VeilingApi/VeilingApi.csproj"
          Write-Host "Using project: $projectPath"
          "buildTarget=$projectPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Restore
        run: dotnet restore "${{ steps.detect.outputs.buildTarget }}"

      - name: Build
        run: dotnet build "${{ steps.detect.outputs.buildTarget }}" -c Release --no-restore

      - name: Publish
        run: dotnet publish "${{ steps.detect.outputs.buildTarget }}" -c Release -o "${{ env.DOTNET_ROOT }}/myapp" --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FloraFlow'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8C95E3573F324621B9D146E9CC74428D }}
